#define MAGIC_NUMBER 'O'

#define NAME_IOCTL_ADD  _IO(MAGIC_NUMBER,8)
#define NAME_IOCTL_SUB  _IO(MAGIC_NUMBER,9)
#define NAME_IOCTL_MUL  _IO(MAGIC_NUMBER,10)
#define NAME_IOCTL_DIV  _IO(MAGIC_NUMBER,11)
